service: etpay-transfers-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  create:
    handler: dist/transfers/create.handler
    events:
      - httpApi:
          path: /transfers
          method: post
  list:
    handler: dist/transfers/list.handler
    events:
      - httpApi:
          path: /transfers
          method: get
  get:
    handler: dist/transfers/get.handler
    events:
      - httpApi:
          path: /transfers/{id}
          method: get
  update:
    handler: dist/transfers/update.handler
    events:
      - httpApi:
          path: /transfers/{id}
          method: put
  delete:
    handler: dist/transfers/delete.handler
    events:
      - httpApi:
          path: /transfers/{id}
          method: delete
